export const PERMISSIONS = {
  // Leads
  LEAD_READ: "LEAD_READ",
  LEAD_CREATE: "LEAD_CREATE",
  LEAD_UPDATE: "LEAD_UPDATE",
  LEAD_DELETE: "LEAD_DELETE",

  // Accounts
  ACCOUNT_READ: "ACCOUNT_READ",
  ACCOUNT_CREATE: "ACCOUNT_CREATE",
  ACCOUNT_UPDATE: "ACCOUNT_UPDATE",

  // Deals
  DEAL_READ: "DEAL_READ",
  DEAL_CREATE: "DEAL_CREATE",
  DEAL_UPDATE: "DEAL_UPDATE",
  DEAL_DELETE: "DEAL_DELETE",
  PIPELINE_READ: "PIPELINE_READ",


  // Users
  USER_MANAGE: "USER_MANAGE",
};

export const ROLE_PERMISSIONS = {
  ADMIN: [...Object.values(PERMISSIONS)],
  MANAGER: [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.ACCOUNT_CREATE,
    PERMISSIONS.ACCOUNT_UPDATE,
    PERMISSIONS.DEAL_READ,
    PERMISSIONS.DEAL_CREATE,
    PERMISSIONS.DEAL_UPDATE,
    PERMISSIONS.PIPELINE_READ,
  ],
  SALES: [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.DEAL_READ,
    PERMISSIONS.DEAL_CREATE,
    PERMISSIONS.PIPELINE_READ,

  ],
};
